// ---------------------------------------------------------------------------
// Local development mock data
// Set NEXT_PUBLIC_USE_MOCK=true in .env.local to use this instead of the API
// ---------------------------------------------------------------------------

export const MOCK_USER = {
  id: 'usr_mock_001',
  googleId: 'google_mock_001',
  email: 'dev@recost.dev',
  name: 'Dev User',
  avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=recost',
  isAdmin: false,
  createdAt: '2025-11-01T00:00:00.000Z',
};

export const MOCK_KEYS = [
  {
    id: 'key_mock_001',
    name: 'local-dev',
    key_prefix: 'eco-a1b2c3d4',
    last_used_at: '2026-03-19T14:22:00.000Z',
    created_at: '2026-01-10T09:00:00.000Z',
  },
];

export const MOCK_PROJECTS = [
  {
    id: 'proj_mock_001',
    name: 'recost-api',
    description: 'Main backend API with AI provider integrations',
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-03-18T16:45:00.000Z',
    latestScanId: 'scan_mock_001',
    summary: { scans: 7, endpoints: 12, callsPerDay: 4820, monthlyCost: 247.85 },
  },
  {
    id: 'proj_mock_002',
    name: 'stripe-integration',
    description: 'Payment flow and billing service',
    createdAt: '2026-02-03T08:30:00.000Z',
    updatedAt: '2026-03-10T11:20:00.000Z',
    latestScanId: 'scan_mock_002',
    summary: { scans: 3, endpoints: 6, callsPerDay: 1340, monthlyCost: 34.20 },
  },
  {
    id: 'proj_mock_003',
    name: 'internal-tools',
    description: 'Admin dashboard and internal utilities',
    createdAt: '2026-03-01T12:00:00.000Z',
    updatedAt: '2026-03-01T12:00:00.000Z',
    latestScanId: undefined,
    summary: { scans: 0, endpoints: 0, callsPerDay: 0, monthlyCost: 0 },
  },
];

export const MOCK_LATEST_SCAN = {
  id: 'scan_mock_001',
  projectId: 'proj_mock_001',
  createdAt: '2026-03-18T16:45:00.000Z',
  endpointIds: [],
  suggestionIds: [],
  graph: { nodes: [], edges: [] },
  summary: {
    totalEndpoints: 12,
    totalCallsPerDay: 4820,
    totalMonthlyCost: 247.85,
    highRiskCount: 3,
  },
};

export const MOCK_ENDPOINTS = [
  {
    id: 'ep_001',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'OpenAI',
    method: 'POST',
    url: 'https://api.openai.com/v1/chat/completions',
    files: ['src/services/ai.ts'],
    callSites: [{ file: 'src/services/ai.ts', line: 42, library: 'openai', frequency: 'high' }],
    callsPerDay: 1200,
    monthlyCost: 98.50,
    status: 'n_plus_one_risk',
  },
  {
    id: 'ep_002',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Anthropic',
    method: 'POST',
    url: 'https://api.anthropic.com/v1/messages',
    files: ['src/services/claude.ts'],
    callSites: [{ file: 'src/services/claude.ts', line: 18, library: '@anthropic-ai/sdk', frequency: 'medium' }],
    callsPerDay: 450,
    monthlyCost: 67.20,
    status: 'normal',
  },
  {
    id: 'ep_003',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'OpenAI',
    method: 'POST',
    url: 'https://api.openai.com/v1/embeddings',
    files: ['src/services/search.ts', 'src/workers/index-worker.ts'],
    callSites: [{ file: 'src/services/search.ts', line: 91, library: 'openai', frequency: 'high' }],
    callsPerDay: 540,
    monthlyCost: 59.05,
    status: 'rate_limit_risk',
  },
  {
    id: 'ep_004',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Cohere',
    method: 'POST',
    url: 'https://api.cohere.ai/v1/generate',
    files: ['src/services/summarise.ts'],
    callSites: [{ file: 'src/services/summarise.ts', line: 33, library: 'cohere-ai', frequency: 'medium' }],
    callsPerDay: 230,
    monthlyCost: 23.10,
    status: 'batchable',
  },
  {
    id: 'ep_005',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Stripe',
    method: 'GET',
    url: 'https://api.stripe.com/v1/customers',
    files: ['src/billing/customers.ts'],
    callSites: [{ file: 'src/billing/customers.ts', line: 57, library: 'stripe', frequency: 'high' }],
    callsPerDay: 890,
    monthlyCost: 0,
    status: 'cacheable',
  },
  {
    id: 'ep_006',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Stripe',
    method: 'POST',
    url: 'https://api.stripe.com/v1/charges',
    files: ['src/billing/payments.ts'],
    callSites: [{ file: 'src/billing/payments.ts', line: 14, library: 'stripe', frequency: 'low' }],
    callsPerDay: 320,
    monthlyCost: 0,
    status: 'normal',
  },
  {
    id: 'ep_007',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'GitHub',
    method: 'GET',
    url: 'https://api.github.com/repos/{owner}/{repo}/commits',
    files: ['src/integrations/github.ts'],
    callSites: [{ file: 'src/integrations/github.ts', line: 22, library: 'octokit', frequency: 'medium' }],
    callsPerDay: 780,
    monthlyCost: 0,
    status: 'redundant',
  },
  {
    id: 'ep_008',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Anthropic',
    method: 'POST',
    url: 'https://api.anthropic.com/v1/complete',
    files: ['src/services/legacy-claude.ts'],
    callSites: [{ file: 'src/services/legacy-claude.ts', line: 8, library: '@anthropic-ai/sdk', frequency: 'low' }],
    callsPerDay: 230,
    monthlyCost: 0,
    status: 'normal',
  },
  {
    id: 'ep_009',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'SendGrid',
    method: 'GET',
    url: 'https://api.sendgrid.com/v3/stats',
    files: ['src/notifications/email.ts'],
    callSites: [{ file: 'src/notifications/email.ts', line: 77, library: '@sendgrid/mail', frequency: 'low' }],
    callsPerDay: 180,
    monthlyCost: 0,
    status: 'redundant',
  },
  {
    id: 'ep_010',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'OpenAI',
    method: 'GET',
    url: 'https://api.openai.com/v1/models',
    files: ['src/config/providers.ts'],
    callSites: [{ file: 'src/config/providers.ts', line: 5, library: 'openai', frequency: 'low' }],
    callsPerDay: 340,
    monthlyCost: 0,
    status: 'cacheable',
  },
  {
    id: 'ep_011',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Stripe',
    method: 'PATCH',
    url: 'https://api.stripe.com/v1/customers/{id}',
    files: ['src/billing/customers.ts'],
    callSites: [{ file: 'src/billing/customers.ts', line: 103, library: 'stripe', frequency: 'low' }],
    callsPerDay: 155,
    monthlyCost: 0,
    status: 'normal',
  },
  {
    id: 'ep_012',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    provider: 'Stripe',
    method: 'DELETE',
    url: 'https://api.stripe.com/v1/customers/{id}',
    files: ['src/billing/customers.ts'],
    callSites: [{ file: 'src/billing/customers.ts', line: 128, library: 'stripe', frequency: 'low' }],
    callsPerDay: 45,
    monthlyCost: 0,
    status: 'normal',
  },
];

export const MOCK_SUGGESTIONS = [
  {
    id: 'sug_001',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    type: 'n_plus_one',
    severity: 'high',
    affectedEndpoints: ['ep_001'],
    affectedFiles: ['src/services/ai.ts'],
    estimatedMonthlySavings: 42.30,
    description: 'chat/completions is called in a loop — batch requests or cache repeated prompts to reduce call volume by ~60%',
    codeFix: '// Before\nfor (const item of items) {\n  await openai.chat.completions.create({ messages: [...] });\n}\n\n// After\nconst results = await Promise.all(\n  chunk(items, 20).map(batch => openai.chat.completions.create({ messages: batch }))\n);',
  },
  {
    id: 'sug_002',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    type: 'rate_limit',
    severity: 'high',
    affectedEndpoints: ['ep_003'],
    affectedFiles: ['src/services/search.ts'],
    estimatedMonthlySavings: 18.75,
    description: 'Embeddings endpoint is called at high frequency without retry logic — add exponential backoff and a request queue to avoid 429s',
    codeFix: '// Add a queue with rate limiting\nimport PQueue from "p-queue";\nconst queue = new PQueue({ interval: 60_000, intervalCap: 3000 });\n\nexport const embed = (text: string) =>\n  queue.add(() => openai.embeddings.create({ input: text, model: "text-embedding-3-small" }));',
  },
  {
    id: 'sug_003',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    type: 'cache',
    severity: 'medium',
    affectedEndpoints: ['ep_005', 'ep_010'],
    affectedFiles: ['src/billing/customers.ts', 'src/config/providers.ts'],
    estimatedMonthlySavings: 12.40,
    description: 'GET /customers and GET /models responses are static or rarely change — cache with a short TTL to cut 890 redundant calls/day',
    codeFix: '// Cache customer list for 60s\nconst customers = await cache.getOrSet(\n  "stripe:customers",\n  () => stripe.customers.list(),\n  { ttl: 60 }\n);',
  },
  {
    id: 'sug_004',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    type: 'batch',
    severity: 'medium',
    affectedEndpoints: ['ep_004'],
    affectedFiles: ['src/services/summarise.ts'],
    estimatedMonthlySavings: 8.20,
    description: 'Cohere generate is called once per document — use the batch API to process up to 96 texts per request',
    codeFix: '// Before: one call per doc\nfor (const doc of docs) {\n  await cohere.generate({ prompt: doc });\n}\n\n// After: batched\nawait cohere.batch.generate({ prompts: docs });',
  },
  {
    id: 'sug_005',
    projectId: 'proj_mock_001',
    scanId: 'scan_mock_001',
    type: 'redundancy',
    severity: 'low',
    affectedEndpoints: ['ep_007', 'ep_009'],
    affectedFiles: ['src/integrations/github.ts', 'src/notifications/email.ts'],
    estimatedMonthlySavings: 3.10,
    description: 'GET /commits and GET /stats are called from 3 different modules with identical parameters — deduplicate with a shared fetch layer',
    codeFix: '// Centralise in a shared provider module\nimport { githubClient } from "@/lib/github";\nconst commits = await githubClient.getCommits(owner, repo); // cached internally',
  },
];

export const MOCK_COST_BY_PROVIDER = [
  { provider: 'OpenAI',    monthlyCost: 157.55, callsPerDay: 2080, endpointCount: 3 },
  { provider: 'Anthropic', monthlyCost:  67.20, callsPerDay:  680, endpointCount: 2 },
  { provider: 'Cohere',    monthlyCost:  23.10, callsPerDay:  230, endpointCount: 1 },
  { provider: 'Stripe',    monthlyCost:   0,    callsPerDay: 1410, endpointCount: 4 },
  { provider: 'GitHub',    monthlyCost:   0,    callsPerDay:  780, endpointCount: 1 },
  { provider: 'SendGrid',  monthlyCost:   0,    callsPerDay:  180, endpointCount: 1 },
];

export const MOCK_COST_BY_FILE = [
  { file: 'src/services/ai.ts',           monthlyCost: 98.50, callsPerDay: 1200, endpointCount: 1 },
  { file: 'src/services/claude.ts',       monthlyCost: 67.20, callsPerDay:  450, endpointCount: 1 },
  { file: 'src/services/search.ts',       monthlyCost: 29.53, callsPerDay:  270, endpointCount: 1 },
  { file: 'src/services/summarise.ts',    monthlyCost: 23.10, callsPerDay:  230, endpointCount: 1 },
  { file: 'src/billing/customers.ts',     monthlyCost:  0,    callsPerDay: 1090, endpointCount: 3 },
  { file: 'src/integrations/github.ts',   monthlyCost:  0,    callsPerDay:  780, endpointCount: 1 },
  { file: 'src/workers/index-worker.ts',  monthlyCost: 29.52, callsPerDay:  270, endpointCount: 1 },
  { file: 'src/notifications/email.ts',   monthlyCost:  0,    callsPerDay:  180, endpointCount: 1 },
  { file: 'src/config/providers.ts',      monthlyCost:  0,    callsPerDay:  340, endpointCount: 1 },
];

export const MOCK_SCANS = [
  {
    id: 'scan_mock_001',
    projectId: 'proj_mock_001',
    createdAt: '2026-03-18T16:45:00.000Z',
    endpointIds: MOCK_ENDPOINTS.map(e => e.id),
    suggestionIds: MOCK_SUGGESTIONS.map(s => s.id),
    graph: { nodes: [], edges: [] },
    summary: { totalEndpoints: 12, totalCallsPerDay: 4820, totalMonthlyCost: 247.85, highRiskCount: 3 },
  },
  {
    id: 'scan_mock_001b',
    projectId: 'proj_mock_001',
    createdAt: '2026-03-10T09:30:00.000Z',
    endpointIds: [],
    suggestionIds: [],
    graph: { nodes: [], edges: [] },
    summary: { totalEndpoints: 10, totalCallsPerDay: 4100, totalMonthlyCost: 210.40, highRiskCount: 2 },
  },
];
